version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8010:80"
    volumes:
      - ./static-content:/usr/share/nginx/html:ro
    networks:
      - nginx_network
  registry:
    image: registry:latest
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry_data:/var/lib/registry

networks:
  nginx_network:
    driver: bridge
  registry_data:
    driver: local
