---
- name: Ensure Python dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Upgrade pip
  command: "/usr/bin/pip3 install --upgrade pip --force-reinstall"

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
    executable: "/usr/bin/pip3"

- name: Install compatible urllib3
  pip:
    name: "urllib3==1.26.14"
    state: present
    executable: "/usr/bin/pip3"

