version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 3000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-home:/var/jenkins_home

volumes:
  jenkins-home:

