apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-web-server
  template:
    metadata:
      labels:
        app: python-web-server
    spec:
      containers:
      - name: python-web-server
        image: maxtsymbaliuk/python-web-server:latest
        ports:
        - containerPort: 8000
