apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxtsymbaliuk-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maxtsymbaliuk-nginx
  template:
    metadata:
      labels:
        app: maxtsymbaliuk-nginx
    spec:
      containers:
      - name: maxtsymbaliuk-nginx
        image: maxtsymbaliuk/maxtsymbaliuk-nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: maxtsymbaliuk-nginx-config
      imagePullSecrets:
      - name: maxtsymbaliuk-regcred
