Vagrant.configure("2") do |config|

  # Jenkins server VM
  config.vm.define "jenkins-master" do |master|
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.network "private_network", type: "dhcp"
    master.vm.hostname = "jenkins-master"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    master.vm.provision "shell", path: "master.sh"
  end

  # Jenkins worker VM
  config.vm.define "jenkins-worker" do |worker|
    worker.vm.box = "bento/ubuntu-22.04"
    worker.vm.network "private_network", type: "dhcp"
    worker.vm.hostname = "jenkins-worker"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    worker.vm.provision "shell", path: "worker.sh"
  end
end

