# homework-20240620/services/yourhostel-nginx-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: maxtsymbaliuk-nginx-service
  namespace: maxtsymbaliuk-namespace
spec:
  selector:
    app: yourhostel-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort


