groups:
- name: example
  rules:
  - alert: HighCpuUsage
    expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 10
    for: 1m
    labels:
      severity: critical
    annotations:
      description: "CPU usage is above 10%"
      summary: "High CPU Usage"
