---
- name: Ensure Python dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Upgrade pip
  yum:
    name: python3-pip
    state: latest

- name: Install Docker SDK for Python
  dnf:
    name: docker
    state: present

- name: Install compatible urllib3
  pip:
    name: "urllib3==1.26.4"
    state: present
    executable: "/usr/bin/pip3"

