version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 3000:8080
    volumes:
      - jenkins-home:/var/jenkins_home

  slave:
    image: jenkins/agent:latest
    user: root
    volumes:
      - jenkins-slave:/var/jenkins_home
    command: >
      java -jar /usr/share/jenkins/agent.jar
        -url http://jenkins:8080
        -secret 0570a7a8cce90c22441190accfe9637647b6d16f269d63ccb2fbab70f6e80a33
        -name "slave-01"
        -workDir "/var/jenkins_home"

volumes:
  jenkins-home:
  jenkins-slave:
