version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 3000:8080
    volumes:
      - jenkins-home:/var/jenkins_home

  slave:
    image: jenkins/agent:latest
    user: root
    volumes:
      - jenkins-slave:/var/jenkins_home
    command: >
      java -jar /usr/share/jenkins/agent.jar
        -url http://jenkins:8080
        -secret fb2ea7f02bc09e07da3e13a9f25d63cda859d26d3f5e026364d1723edcc69e18
        -name "slave-01"
       -workDir "/var/jenkins_home"

volumes:
  jenkins-home:
  jenkins-slave:
